### ISSUE TITLE
[Questions] I Have Some Questions

### ISSUE THREAD

**Issue by ditokp** [snollygolly/IsoCitySim#5]
Hello, today I searching the simulation game in Github and I find your game. After see the screenshot in the readme, I'm really happy because I found city simulation game with good graphics. But after I check the demo website, I confused, I can't place/remove building, road, etc. My questions is:

1) Is this really a game? or just city generator?
2) Is this game still being developed? Because the latest commit is from 2017.

Thank you very much for reading my issue.

**Comment by snollygolly** [comment]
Hey there! I’m glad you enjoy it. To answer your questions:

1. It’s not a game, just a city generator. It could be turned into a game, but it isn’t currently. Objects are semi-randomly places and can’t be changed without a reload. 

2. Nope. I’m on to other things, but I think it’s still a cool project which is why I have it up.

**Comment by ditokp** [comment]
Sorry for late reply, and thank you for answering my questions. Have a nice day :-)
